// 全站 RootLayout：載入全域字體/樣式，包住 ProductProvider 與 AuthProvider
import { Noto_Sans_TC } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "@/styles/globals.css";
import Script from "next/script";
import { AuthProvider } from "@/hooks/use-auth";
import { ProductProvider } from "@/hooks/use-product";


const notoSansTC = Noto_Sans_TC({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-noto-sans-tc",
});

export const metadata = {
  title: "Thync",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="zh-Hant">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
          strategy="afterInteractive"
        />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
          integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg=="
          crossOrigin="anonymous" referrerPolicy="no-referrer" />
      </head>
      <ProductProvider>
        <AuthProvider>
          <body className={notoSansTC.variable}>
            {children}
          </body>
        </AuthProvider>
      </ProductProvider>
    </html>
  );
}
